### PR TITLE
Update SRL API and models to support LTP 3.4.0

### PR DESCRIPTION
**Pull request by liu946**
## Description Changes

1. Remove ltp_data folder. Users need to download models.
2. Update submodule ltp to 3.4.0 and change pyltp apis.
3. Update patch boost and python version.
4. Add travis python 3.6 check.

## Motivation and Context

1. Update pyltp to support ltp 3.4.0
2. #101 #96 #95 #94 #72 #56 #52

## How Has This Been Tested?

travis python 2.6 2.7 and 3.4 to 3.6.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by memeda** [comment]
https://stackoverflow.com/questions/3047542/building-lxml-for-python-2-7-on-windows/5122521#5122521

python2.7 使用vs2008编译的，一般也要求扩展用vs2008编译；然而这个版本的编译器不支持C++11，所以编译DyNet报错了。

不知道有没有救，暂时没有搜到有用的信息。不知道有没有什么trick

**Comment by Oneplus** [comment]
@memeda 我觉得没救了

**Comment by liu946** [comment]
我在文档中加一下note，之后直接merge了吧。

**Comment by Oneplus** [comment]
@liu946 应该改一下windows的ci

**Comment by liu946** [comment]
@Oneplus appveyor这个权限控制有点问题。我没办法编辑这个ci的配置。

**Comment by Oneplus** [comment]
@liu946 可以直接改appveyor.yml。配置里也没法配置python。

**Pull request merged**
